apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-4mhm
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0005-tenant/tkrw-pr712-0075-0005-app/devfile-sample-4mhm@sha256:04a7a4ef22a2b6c2847e30742ffeb27f81010878ed5ae6292a53a5fed346ff8c
        name: my-nodejs
        resources: {}
status: {}
